FROM python:bookworm

ADD main.py .

RUN pip install plotly_express dash

EXPOSE 8050

CMD ["python", "main.py"] 











### RUN pip install -U setuptools

#ADD index.html .

# CMD ["python", "-m", "http.server"]
